#### 2023.8.14 | Javascript - Promise, async/await

#### Promise 체이닝(chaining)

여러 개의 Promise를 연속적으로 연결해서 작업을 순차적으로 실행하고 결과를 다루는 방식이다. 비동기 작업을 순차적으로 연결하여 처리하는 하며 콜백 헬과 같은 문제를 피하면서 코드를 더 깔끔하게 작성할 수 있다. 

Promise 체이닝의 핵심은 'then' 메서드를 사용하여 여러 비동기 작업을 연결하는 것이다. 각 'then'메서드는 새로운 Promise를 반환하므로 이 Promise에 다시 'then' 메서드를 연결할 수 있다.

```javascript
fetch('https://jsonplaceholder.typicode.com/todos?_limit=5')
  .then(response => {
    return response.json()
  })
  .then(data => {
    console.log('data ', data)
    return data.filter(obj => obj.id > 3)
  })
  .then(result => {
    console.log('result: ', result)
  })
  .catch(err => {
    console.log('err: ', err)
  })
  .finally(() => {
    console.log('### finally ###')
  })
```

예) 콜백 헬
```javascript
function getUser(userId) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      try {
        const user = { id: userId, name: 'Adam' };
        resolve(user)
      } catch (error) {
        reject(error)
      }
    }, 1000)
  });
}

function getPosts(userId, callback) {
  new Promise((resolve, reject) => {
    setTimeout(() => {
      const posts = [
        {id: 1, title = 'Post 1'},
        {id: 2, title = 'Post 2'},
      ]
      resolve(posts)
    }, 1000);
  })
}

function getComments(postId, callback) {
  return new Promise(resolve, rejet) => {
    setTimeout(() => {
      const comments = [
        {id: 1, text: 'Comment 1'},
        {id: 2, text: 'Comment 2'},
        {id: 3, text: 'Comment 3'},
      ]
      resolve(comments)
    }, 1000)
  })
}

// getUser(1, (user) => {
//   console.log('user: ', user)
//   getPosts(user.id, (posts) => {
//     console.log('posts: ', posts)
//     getComments(posts[0].id, (comments) => {
//       console.log('comments: ', comments)
//     })
//   })
// })

getUser(1)
  .then((user) => {
    console.log('user: ', user)
    return getPosts(user.id);
  })
  .then((posts) => {
    console.log('posts: ', posts)
    return getComments(posts[0].id)
  })
  .then((comments) => {
    console.log('comments: ', comments)
  })
  .catch(err => console.log('err: ', err))
  .finally(() => console.log('### finally ###'))
```